version: "3.7"

services:
  php:
    build:
      context: .docker/php/8.0
    container_name: icehawk_php
    volumes:
      - ./:/app

  composer:
    image: library/composer:2
    container_name: icehawk_composer
    volumes:
      - ./:/app
    command: update -o -v --ignore-platform-reqs

  phive:
    image: hyperized/phive:latest
    restart: 'no'
    volumes:
      - ./:/app
      - phive:/root/.phive
    working_dir: /app

volumes:
  phive:
