version: "3"

services:
  php72:
    build:
      context: .docker/php/7.2
    volumes:
      - ./:/code

  php73:
    build:
      context: .docker/php/7.3
    volumes:
      - ./:/code

  php74:
    build:
      context: .docker/php/7.4
    volumes:
      - ./:/code